import { Context, Resource } from "../core/Common.js";
import { Document, DocumentWritable, Statement } from "../core/Document.js";
export declare class DocumentImpl<ContainedStatement extends Statement = Statement, SelfDescribingStatement extends Statement = Statement> implements DocumentWritable<ContainedStatement, SelfDescribingStatement> {
    createStatement(about: string, value: string): ThisType<this>;
    addStatement(other: ContainedStatement): ThisType<this>;
    addStatementAll(others: Iterable<Statement>): ThisType<this>;
    createStatementAboutSelf(value: string): ThisType<this>;
    addStatementAboutSelf(other: ContainedStatement): ThisType<this>;
    addStatementAboutSelfAll(others: Iterable<Statement>): ThisType<this>;
    delete(element: ContainedStatement): ThisType<this>;
    deleteMatches(uri?: string | Resource | undefined, property?: string | undefined, value?: string | undefined): ThisType<this>;
    pop(): ContainedStatement | undefined;
    reverse(): void;
    shift(): ContainedStatement | undefined;
    sort(compareFn?: ((a: ContainedStatement, b: ContainedStatement) => number) | undefined): ThisType<this>;
    splice(start: number, deleteCount?: number | undefined, ...items: ContainedStatement[]): ThisType<this>;
    getStatement(about: string, property: string): ContainedStatement;
    getStatementAll(about: string, property: string): ContainedStatement[];
    getStatementAboutSelf(property: string): SelfDescribingStatement;
    getStatementAboutSelfAll(property: string): SelfDescribingStatement[];
    hasStatement(about: string, property: string): boolean;
    hasStatementAboutSelf(): boolean;
    at(index: number): ContainedStatement | undefined;
    contains(other: Document): boolean;
    count(): number;
    every(predicate: (value: ContainedStatement, index?: number | undefined, array?: ContainedStatement[] | undefined) => boolean, thisArg?: any): boolean;
    filter(predicate: (value: ContainedStatement, index?: number | undefined, array?: ContainedStatement[] | undefined) => boolean): ContainedStatement[];
    find(predicate: (value: ContainedStatement, index?: number | undefined, obj?: ContainedStatement[] | undefined) => boolean, thisArg?: any): ContainedStatement | undefined;
    findIndex(predicate: (value: ContainedStatement, index?: number | undefined, obj?: ContainedStatement[] | undefined) => unknown, thisArg?: any): number;
    forEach(callbackfn: (value: ContainedStatement, index?: number | undefined, array?: ContainedStatement[] | undefined) => void, thisArg?: any): void;
    includes(searchElement: ContainedStatement, fromIndex?: number | undefined): boolean;
    indexOf(searchElement: ContainedStatement, fromIndex?: number | undefined): number;
    keys(): IterableIterator<number>;
    map(callbackfn: (value: ContainedStatement, index?: number | undefined, array?: ContainedStatement[] | undefined) => unknown, thisArg?: any): unknown[];
    reduce(callbackfn: (previousValue: ContainedStatement, currentValue: ContainedStatement, currentIndex: number, array: ContainedStatement[]) => ContainedStatement): ContainedStatement;
    slice(start?: number | undefined, end?: number | undefined): Document;
    some(predicate: (value: ContainedStatement, index?: number | undefined, array?: ContainedStatement[] | undefined) => unknown, thisArg?: any): boolean;
    [Symbol.iterator](): Iterator<ContainedStatement, any, undefined>;
    getUri(): string;
    hasUri(): boolean;
    isEmpty(): boolean;
    getContext(): Context | undefined;
    equals(other: ThisType<this>): boolean;
    difference(other: ThisType<this>): ThisType<this>;
    toCopy(): ThisType<this>;
    deleteContext(): void;
    setContext(context: Context): void;
}
export default DocumentImpl;
//# sourceMappingURL=DocumentImpl.d.ts.map