import Resource from "../core/Resource";
import Thing from "../core/Thing";
type Constructor<T = {}> = new (...args: any[]) => T;
export declare function ThingWithHelpersMixin<TBase extends Constructor<Thing>>(Base: TBase): {
    new (...args: any[]): {
        addStatement(about: string, value: string | Resource, datatype?: string, language?: string): any;
        addStatementFrom(source: Thing): any;
        addRdfTypeStatement(value: string): any;
        addBooleanStatement(about: string, value: boolean): any;
        addStringStatement(about: string, value: string, locale?: string): any;
        addDecimalStatement(about: string, value: number): any;
        addIntegerStatement(about: string, value: number): any;
        addDateStatement(about: string, value: Date): any;
        addDatetimeStatement(about: string, value: Date): any;
        addTimeStatement(about: string, value: Date): any;
        getRdfTypeValue(): string | null;
        getAllRdfTypeValues(): string[];
        getBooleanStatementValue(about: string): boolean;
        getAllBooleanStatementValues(about: string): boolean[];
        getStringStatementValue(about: string): string | null;
        getAllStringStatementValues(about: string): string[];
        getDecimalStatementValue(about: string): number;
        getAllDecimalStatementValues(about: string): number[];
        getIntegerStatementValue(about: string): number;
        getAllIntegerStatementValues(about: string): number[];
        getDateStatementValue(about: string): Date;
        getAllDateStatementValues(about: string): Date[];
        getDatetimeStatementValue(about: string): Date;
        getAllDatetimeStatementValues(about: string): Date[];
        getTimeStatementValue(about: string): Date;
        getAllTimeStatementValues(about: string): Date[];
        setStatement(about: string, value: string): any;
        setRdfTypeStatement(value: string): any;
        setBooleanStatement(about: string, value: boolean): any;
        setStringStatement(about: string, value: string, locale?: string): any;
        setDecimalStatement(about: string, value: number): any;
        setIntegerStatement(about: string, value: number): any;
        setDateStatement(about: string, value: Date): any;
        setDatetimeStatement(about: string, value: Date): any;
        setTimeStatement(about: string, value: Date): any;
        removeStatement(about: string, value: string | Resource, datatype?: string, language?: string): any;
        removeRdfTypeStatement(value: string): any;
        removeBooleanStatement(about: string, value: boolean): any;
        removeStringStatement(about: string, value: string, locale?: string): any;
        removeDecimalStatement(about: string, value: number): any;
        removeIntegerStatement(about: string, value: number): any;
        removeDateStatement(about: string, value: Date): any;
        removeDatetimeStatement(about: string, value: Date): any;
        removeTimeStatement(about: string, value: Date): any;
        getDocument(): import("../core/Document").Document<any, any>;
        getContext(): import("../index").Context | undefined;
        hasUri(): boolean;
        count(): number;
        isEmpty(): boolean;
        equals(other: import("../core/Thing").ThingBase): boolean;
        get(property: string): string;
        getAll(property: string): string[];
        [Symbol.iterator](): Iterator<import("../core/Statement").Statement, any, undefined>;
        getUri(): string;
        forEach(callbackfn: (value: import("../core/Statement").Statement, index: number, array: import("../core/Statement").Statement[]) => void, thisArg?: any): void;
        map(callbackfn: (value: import("../core/Statement").Statement, index: number, array: import("../core/Statement").Statement[]) => unknown, thisArg?: any): unknown[];
        filter(predicate: (value: import("../core/Statement").Statement, index: number, array: import("../core/Statement").Statement[]) => boolean): import("../core/Statement").Statement[];
        add(about: string, value: string | Resource, datatype?: string | undefined, language?: string | undefined): Thing;
        remove(about: string, value: string | Resource, datatype?: string | undefined, language?: string | undefined): Thing;
        removeAll(about: string): Thing;
        set(about: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): Thing;
    };
} & TBase;
export default ThingWithHelpersMixin;
//# sourceMappingURL=ThingWithHelpersMixin.d.ts.map