import { Resource } from "../core/Common";
import { Thing } from "../core/Thing";
type Constructor<T = {}> = new (...args: any[]) => T;
export declare function ThingWithHelpersMixin<TBase extends Constructor<Thing<any>>>(Base: TBase): {
    new (...args: any[]): {
        addStatement(about: string, value: string | Resource, datatype?: string, language?: string): any;
        addStatementFrom(source: Thing<any>): any;
        addRdfTypeStatement(value: string): any;
        addBooleanStatement(about: string, value: boolean): any;
        addStringStatement(about: string, value: string, locale?: string): any;
        addDecimalStatement(about: string, value: number): any;
        addIntegerStatement(about: string, value: number): any;
        addDateStatement(about: string, value: Date): any;
        addDatetimeStatement(about: string, value: Date): any;
        addTimeStatement(about: string, value: Date): any;
        getRdfTypeValue(): string | null;
        getAllRdfTypeValues(): string[];
        getBooleanStatementValue(about: string): boolean;
        getAllBooleanStatementValues(about: string): boolean[];
        getStringStatementValue(about: string): string | null;
        getAllStringStatementValues(about: string): string[];
        getDecimalStatementValue(about: string): number;
        getAllDecimalStatementValues(about: string): number[];
        getIntegerStatementValue(about: string): number;
        getAllIntegerStatementValues(about: string): number[];
        getDateStatementValue(about: string): Date;
        getAllDateStatementValues(about: string): Date[];
        getDatetimeStatementValue(about: string): Date;
        getAllDatetimeStatementValues(about: string): Date[];
        getTimeStatementValue(about: string): Date;
        getAllTimeStatementValues(about: string): Date[];
        setStatement(about: string, value: string): any;
        setRdfTypeStatement(value: string): any;
        setBooleanStatement(about: string, value: boolean): any;
        setStringStatement(about: string, value: string, locale?: string): any;
        setDecimalStatement(about: string, value: number): any;
        setIntegerStatement(about: string, value: number): any;
        setDateStatement(about: string, value: Date): any;
        setDatetimeStatement(about: string, value: Date): any;
        setTimeStatement(about: string, value: Date): any;
        removeStatement(about: string, value: string | Resource, datatype?: string, language?: string): any;
        removeRdfTypeStatement(value: string): any;
        removeBooleanStatement(about: string, value: boolean): any;
        removeStringStatement(about: string, value: string, locale?: string): any;
        removeDecimalStatement(about: string, value: number): any;
        removeIntegerStatement(about: string, value: number): any;
        removeDateStatement(about: string, value: Date): any;
        removeDatetimeStatement(about: string, value: Date): any;
        removeTimeStatement(about: string, value: Date): any;
        getStatement(property: string, language?: string | undefined): any;
        getStatementAll(property?: string | undefined, language?: string | undefined): any[];
        hasStatement(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: Thing<import("../core/Statement").Statement>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => any): any;
        slice(start?: number | undefined, end?: number | undefined): Thing<import("../core/Statement").Statement>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
    };
} & TBase;
export default ThingWithHelpersMixin;
//# sourceMappingURL=ThingWithHelpersMixin.d.ts.map