import { DocumentWritableConstructor } from "../core/Document";
import { Statement } from "../core/Statement";
import { Thing } from "../core/Thing";
import { Changelog } from "./Changelog";
import { ChangelogImpl } from "./ChangelogImpl.js";
export declare function DocumentWithChangelogMixin<TBase extends DocumentWritableConstructor<any, any>>(Base: TBase): {
    new (...args: any[]): {
        _changelog: ChangelogImpl;
        createStatement(about: string | Thing, property: string, value: string, datatype?: string, language?: string): Statement | undefined;
        getChangelog(): Changelog;
        createThing(): any;
        createThingAboutSelf(): any;
        addThing(other: Thing<Statement>): any;
        addThingAll(others: Iterable<Thing<Statement>>): any[];
        addThingAboutSelf(other: Thing<Statement>): any;
        addThingAboutSelfAll(others: Iterable<Thing<Statement>>): any[];
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): Statement;
        addStatement(other: Statement): Statement;
        addStatementAll(others: Iterable<Statement>): Statement[];
        addStatementAboutSelf(other: Statement): Statement;
        addStatementAboutSelfAll(others: Iterable<Statement>): Statement[];
        setStatement(about: any, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): Statement | undefined;
        setStatementAboutSelf(value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): Statement | undefined;
        deleteThing(thingOrUri: string | Thing<Statement>): boolean;
        deleteStatement(statement: Statement): boolean;
        pop(): any;
        reverse(): void;
        shift(): any;
        sort(compareFn?: ((a: any, b: any) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined, ...items: any[]): ThisType<any>;
        getThing(about: string): any;
        getThingAboutSelf(): any;
        hasThing(about: string): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | Thing<Statement>, property: string, language?: string | undefined): Statement | undefined;
        getStatementAll(about: string | Thing<Statement>, property?: string | undefined, language?: string | undefined): Statement[];
        getStatementAboutSelf(property: string, language?: string | undefined): Statement | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): Statement[];
        hasStatement(about: string | Thing<Statement>, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: import("../core/Document").Document<any, Thing<Statement>>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        filterContainedStatement(predicate: (value: Statement, index?: number | undefined, array?: Statement[] | undefined) => boolean): Statement[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: Statement, index?: number | undefined, array?: Statement[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => Thing<Statement>): any;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        deleteContext(): void;
        setContext(context: import("../core/Common").Context): void;
    };
} & TBase;
//# sourceMappingURL=DocumentWithChangelogImpl.d.ts.map