import { DocumentWithChangelogConstructor } from "../changelog/Changelog";
export declare function DocumentWithChangelogN3Mixin<TBase extends DocumentWithChangelogConstructor<any, any>>(Base: TBase): {
    new (...args: any[]): {
        toN3(): string;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        getThing(about: string | import("../core/Common").Resource): any;
        getThingAboutSelf(): any;
        hasThing(about: string | import("../core/Common").Resource): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | import("../core/Common").Resource, property: string, language?: string | undefined): import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations;
        getStatementAll(about: string | import("../core/Common").Resource, property?: string | undefined, language?: string | undefined): (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations)[];
        getStatementAboutSelf(property: string, language?: string | undefined): (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations) | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations)[];
        hasStatement(about: string | import("../core/Common").Resource, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: import("../core/Document").DocumentWithNonDestructiveOperations<any, import("../core/Thing").ThingWithNonDestructiveOperations<import("../core/Statement").StatementWithDestructiveOperations>>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        filterContainedStatement(predicate: (value: import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations, index?: number | undefined, array?: (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations)[] | undefined) => boolean): (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations)[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations, index?: number | undefined, array?: (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations)[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => import("../core/Thing").ThingWithNonDestructiveOperations<import("../core/Statement").StatementWithDestructiveOperations>): any;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        createThing(uriOrNameHint?: string | import("../core/Common").Resource | undefined): any;
        createThingAboutSelf(): any;
        addThing(other: import("../core/Thing").ThingWithNonDestructiveOperations<import("../core/Statement").StatementWithDestructiveOperations>): any;
        addThingAll(others: Iterable<import("../core/Thing").ThingWithNonDestructiveOperations<import("../core/Statement").StatementWithDestructiveOperations>>): any[];
        addThingAboutSelf(other: import("../core/Thing").ThingWithNonDestructiveOperations<import("../core/Statement").StatementWithDestructiveOperations>): any;
        addThingAboutSelfAll(others: Iterable<import("../core/Thing").ThingWithNonDestructiveOperations<import("../core/Statement").StatementWithDestructiveOperations>>): any[];
        createStatement(about: string | import("../core/Common").Resource, property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations;
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations;
        addStatement(other: import("../core/Statement").StatementWithDestructiveOperations): import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations;
        addStatementAll(others: Iterable<import("../core/Statement").StatementWithDestructiveOperations>): (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations)[];
        addStatementAboutSelf(other: import("../core/Statement").StatementWithDestructiveOperations): import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations;
        addStatementAboutSelfAll(others: Iterable<import("../core/Statement").StatementWithDestructiveOperations>): (import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations)[];
        setThing(thing: any, uri?: string | undefined): any;
        setThingAt(index: number, thing: any): any;
        setStatement(about: string | import("../core/Common").Resource, property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations;
        setStatementAboutSelf(property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Common").Resource & import("../core/Common").Copyable & import("../core/Statement").StatementNonDestructiveOperations & import("../core/Statement").StatementDestructiveOperations;
        removeThing(thingOrUri: string | import("../core/Common").Resource): boolean;
        removeStatement(statement: import("../core/Statement").StatementWithDestructiveOperations): boolean;
        removeStatement(about: string | import("../core/Common").Resource, property: string, value: string, language?: string | undefined): boolean;
        pop(): any;
        reverse(): void;
        shift(): any;
        sort(compareFn?: ((a: any, b: any) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined): any[];
        splice(start: number, deleteCount: number, ...items: any[]): any[];
        getChangelog(): import("../changelog/Changelog").Changelog<import("../core/Statement").StatementWithDestructiveOperations>;
    };
} & TBase;
//# sourceMappingURL=ChangelogN3Impl.d.ts.map