import { DocumentWithChangelogN3Constructor } from "../changelog-n3/ChangelogN3";
export declare function LocalSolidDocumentMixin<TBase extends DocumentWithChangelogN3Constructor<any, any>>(Base: TBase): {
    new (...args: any[]): {
        saveUpdate(): Promise<void>;
        saveNew(uri: string): Promise<void>;
        saveOverwrite(): Promise<void>;
        isLocal(): boolean;
        isDistant(): boolean;
        getDistantUri(): string | undefined;
        getDistantUriAll(): string[];
        createThing(uriOrNameHint?: string | import("../core/Common").Resource | undefined): any;
        createThingAboutSelf(): any;
        addThing(other: import("../core/Thing").Thing<import("../core/Statement").Statement>): any;
        addThingAll(others: Iterable<import("../core/Thing").Thing<import("../core/Statement").Statement>>): any[];
        addThingAboutSelf(other: import("../core/Thing").Thing<import("../core/Statement").Statement>): any;
        addThingAboutSelfAll(others: Iterable<import("../core/Thing").Thing<import("../core/Statement").Statement>>): any[];
        createStatement(about: string | import("../core/Common").Resource, property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Statement").Statement;
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Statement").Statement;
        addStatement(other: import("../core/Statement").Statement): import("../core/Statement").Statement;
        addStatementAll(others: Iterable<import("../core/Statement").Statement>): import("../core/Statement").Statement[];
        addStatementAboutSelf(other: import("../core/Statement").Statement): import("../core/Statement").Statement;
        addStatementAboutSelfAll(others: Iterable<import("../core/Statement").Statement>): import("../core/Statement").Statement[];
        setThing(thing: any, uri?: string | undefined): any;
        setThingAt(index: number, thing: any): any;
        setStatement(about: string | import("../core/Common").Resource, property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Statement").Statement;
        setStatementAboutSelf(property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Statement").Statement;
        removeThing(thingOrUri: string | import("../core/Common").Resource): boolean;
        removeStatement(statement: import("../core/Statement").Statement): boolean;
        removeStatement(about: string | import("../core/Common").Resource, property: string, value: string, language?: string | undefined): boolean;
        pop(): any;
        reverse(): void;
        shift(): any;
        sort(compareFn?: ((a: any, b: any) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined): any[];
        splice(start: number, deleteCount: number, ...items: any[]): any[];
        getThing(about: string | import("../core/Common").Resource): any;
        getThingAboutSelf(): any;
        hasThing(about: string | import("../core/Common").Resource): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | import("../core/Common").Resource, property: string, language?: string | undefined): import("../core/Statement").Statement;
        getStatementAll(about: string | import("../core/Common").Resource, property?: string | undefined, language?: string | undefined): import("../core/Statement").Statement[];
        getStatementAboutSelf(property: string, language?: string | undefined): import("../core/Statement").Statement | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): import("../core/Statement").Statement[];
        hasStatement(about: string | import("../core/Common").Resource, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: import("../core/Document").Document<any, import("../core/Thing").Thing<import("../core/Statement").Statement>>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        filterContainedStatement(predicate: (value: import("../core/Statement").Statement, index?: number | undefined, array?: import("../core/Statement").Statement[] | undefined) => boolean): import("../core/Statement").Statement[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: import("../core/Statement").Statement, index?: number | undefined, array?: import("../core/Statement").Statement[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => import("../core/Thing").Thing<import("../core/Statement").Statement>): any;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        deleteContext(): void;
        setContext(context: import("../core/Common").Context): void;
        getChangelogN3(): import("../changelog-n3/ChangelogN3").ChangelogN3<import("../core/Statement").Statement>;
        getChangelog(): import("../changelog/Changelog").Changelog<import("../core/Statement").Statement>;
    };
} & TBase;
//# sourceMappingURL=SynchronizedSolidImpl.d.ts.map