import DatasetExt from "rdf-ext/lib/Dataset";
import Context from "./Context";
import { Document } from "./Document";
import Resource from "./Resource";
import Thing from "./Thing";
export declare class DocumentDefaultImpl implements Document {
    private _uri;
    private _things;
    private _context?;
    constructor(uri?: string, context?: Context);
    [Symbol.iterator](): Iterator<Thing, any, undefined>;
    setContext(context: Context): void;
    getContext(): Context | undefined;
    expand(uri: string): string;
    shorten(uri: string): string;
    addThing(thing: Thing): Document;
    protected setThings(things: Thing[]): void;
    addDocument(document: Document): Document;
    equals(other: Document): boolean;
    getThing(uri: string): Thing | null;
    protected isUrl(input: string): boolean;
    protected generateUriWithFragment(): string;
    protected getOrCreateNameWithHash(nameWithOrWithoutHash: string): string;
    protected createUriWithFragment(name: string): string;
    protected checkUriCanBeAddedToTheDocument(uri: string): boolean;
    protected getSafeUriFromUri(uri: string): string;
    protected getSafeUriFromName(name: string): string;
    protected getSafeUriFromNameHintOrUri(nameHintOrUri: string): string;
    createThingToSelfDescribe(): Thing;
    generateThingName(): string;
    protected validateOrCreateThingUri(nameHintOrUri?: string): string;
    protected validateNameHintForThingWithoutUri(nameHint: string): void;
    protected validateAndCreateThingWithoutUri(nameHint?: string): Thing;
    protected createAndAddRegularThing(uri: string): Thing;
    createThing(nameHintOrUri?: string): Thing;
    createThingWithoutUri(nameHint?: string): Thing;
    deleteThing(thingOrUri: string | Thing): void;
    getUri(): string;
    setUri(uri: string): void;
    isEmpty(): boolean;
    private _getThings;
    getThingsAll(): Thing[];
    getThingThatSelfDescribes(): Thing | null;
    countThings(): number;
    hasStatementsAbout(subject: string | Resource, property?: string, ...hasValues: string[]): boolean;
    filter(predicate: (value: Thing, index: number, array: Thing[]) => boolean): Thing[];
    toRdfDatasetExt(): DatasetExt;
}
export default DocumentDefaultImpl;
//# sourceMappingURL=DocumentDefaultImpl.d.ts.map