import Document from "./Document";
import Thing from "./Thing";
import QuadExt from 'rdf-ext/lib/Quad';
import NamedNodeExt from "rdf-ext/lib/NamedNode";
import Resource from "./Resource";
import Contextualized from "./Contextualized";
import Context from "./Context";
declare class ThingDefaultImpl implements Thing, Contextualized {
    private _uri;
    private _rdfjsDataset;
    private _context?;
    constructor(uri: string, context?: Context);
    getUri(): string;
    setUri(uri: string): void;
    setContext(context: Context): void;
    getContext(): Context | undefined;
    expand(uri: string): string;
    shorten(uri: string): string;
    filter(by: (property?: string, value?: string, datatype?: string) => boolean): Thing;
    private getDataset;
    protected addRdfQuad(quad: QuadExt): void;
    protected createRdfQuad(property: string, value: string | Resource, languageOrDatatype?: string | NamedNodeExt): QuadExt;
    addStatement(about: string, value: string | Resource, datatype?: string, language?: string): Thing;
    addStatementFrom(source: Thing): Thing;
    addRdfTypeStatement(value: string): Thing;
    addBooleanStatement(about: string, value: boolean): Thing;
    addStringStatement(about: string, value: string, locale?: string): Thing;
    addDecimalStatement(about: string, value: number): Thing;
    addIntegerStatement(about: string, value: number): Thing;
    addDateStatement(about: string, value: Date): Thing;
    addDatetimeStatement(about: string, value: Date): Thing;
    addTimeStatement(about: string, value: Date): Thing;
    getAllValuesAboutStatement(property: string): string[];
    getDocument(): Document;
    getRdfTypeValue(): string | null;
    getAllRdfTypeValues(): string[];
    getBooleanStatementValue(about: string): boolean;
    getAllBooleanStatementValues(about: string): boolean[];
    getStringStatementValue(about: string): string | null;
    getAllStringStatementValues(about: string): string[];
    getDecimalStatementValue(about: string): number;
    getAllDecimalStatementValues(about: string): number[];
    getIntegerStatementValue(about: string): number;
    getAllIntegerStatementValues(about: string): number[];
    getDateStatementValue(about: string): Date;
    getAllDateStatementValues(about: string): Date[];
    getDatetimeStatementValue(about: string): Date;
    getAllDatetimeStatementValues(about: string): Date[];
    getTimeStatementValue(about: string): Date;
    getAllTimeStatementValues(about: string): Date[];
    setRdfTypeStatement(value: string): Thing;
    setBooleanStatement(about: string, value: boolean): Thing;
    setStringStatement(about: string, value: string, locale?: string): Thing;
    setDecimalStatement(about: string, value: number): Thing;
    setIntegerStatement(about: string, value: number): Thing;
    setDateStatement(about: string, value: Date): Thing;
    setDatetimeStatement(about: string, value: Date): Thing;
    setTimeStatement(about: string, value: Date): Thing;
    removeAllStatements(about: string): void;
    removeRdfTypeStatement(value: string): void;
    removeBooleanStatement(about: string, value: boolean): void;
    removeStringStatement(about: string, value: string, locale?: string): void;
    removeDecimalStatement(about: string, value: number): void;
    removeIntegerStatement(about: string, value: number): void;
    removeDateStatement(about: string, value: Date): void;
    removeDatetimeStatement(about: string, value: Date): void;
    removeTimeStatement(about: string, value: Date): void;
}
export default ThingDefaultImpl;
//# sourceMappingURL=ThingDefaultImpl.d.ts.map