import { DocumentWithDestructiveOperationsConstructor } from "../core/Document.js";
import { Thing, ThingConstructor } from "../core/Thing.js";
import { TypeIndexRegistration, TypeIndexStatement } from "./types.js";
import { Statement, StatementConstructor } from "../core/Statement.js";
export declare function TypeIndexMixin<TBase extends DocumentWithDestructiveOperationsConstructor<TypeIndexRegistration, Thing<TypeIndexStatement>>>(Base: TBase): {
    new (...args: any[]): {
        getForClassAll(): string[];
        getRegistrationAllForClass(forClass: string): TypeIndexRegistration[];
        getRegistrationAllForInstance(instance: string): TypeIndexRegistration[];
        getRegistrationAllForInstanceContainer(instanceContainer: string): TypeIndexRegistration[];
        createRegistration(): TypeIndexRegistration;
        addForClassToRegistration(registration: string | TypeIndexRegistration, forClass: string): TypeIndexRegistration;
        addInstanceToRegistration(registration: string | TypeIndexRegistration, instance: string): TypeIndexRegistration;
        addInstanceContainerToRegistration(registration: string | TypeIndexRegistration, instanceContainer: string): TypeIndexRegistration;
        setForClassOfRegistration(registration: string | TypeIndexRegistration, forClass: string, oldValue?: string): TypeIndexRegistration;
        setInstanceOfRegistration(registration: string | TypeIndexRegistration, instance: string, oldValue?: string): TypeIndexRegistration;
        setInstanceContainerOfRegistration(registration: string | TypeIndexRegistration, instanceContainer: string, oldValue?: string): TypeIndexRegistration;
        removeForClassOfRegistration(registration: string | TypeIndexRegistration, ...forClasses: string[]): TypeIndexRegistration;
        removeInstanceOfRegistration(registration: string | TypeIndexRegistration, ...instances: string[]): TypeIndexRegistration;
        removeInstanceContainerOfRegistration(registration: string | TypeIndexRegistration, ...instanceContainers: string[]): TypeIndexRegistration;
        removeForClassAllOfRegistration(registration: string | TypeIndexRegistration): TypeIndexRegistration;
        removeInstanceAllOfRegistration(registration: string | TypeIndexRegistration): TypeIndexRegistration;
        removeInstanceContainerAllOfRegistration(registration: string | TypeIndexRegistration): TypeIndexRegistration;
        forEachOfClass(forClass: string, callbackfn: (value: TypeIndexRegistration, index?: number, array?: TypeIndexRegistration[]) => void, thisArg?: any): void;
        createThing(uriOrNameHint?: string): TypeIndexRegistration;
        createRegistrationForInstance(forClass: string, instance: string, nameHintOrUri?: string): TypeIndexRegistration;
        createRegistrationForInstanceContainer(forClass: string, instanceContainer: string, nameHintOrUri?: string): TypeIndexRegistration;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common.js").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        getThing(about: string | import("../core/Common.js").Resource): TypeIndexRegistration;
        getThingAboutSelf(): Thing<TypeIndexStatement>;
        hasThing(about: string | import("../core/Common.js").Resource): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | import("../core/Common.js").Resource, property: string, language?: string | undefined): TypeIndexStatement;
        getStatementAll(about: string | import("../core/Common.js").Resource, property?: string | undefined, language?: string | undefined): TypeIndexStatement[];
        getStatementAboutSelf(property: string, language?: string | undefined): TypeIndexStatement | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): TypeIndexStatement[];
        hasStatement(about: string | import("../core/Common.js").Resource, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): TypeIndexRegistration | undefined;
        contains(other: import("../core/Document.js").DocumentWithNonDestructiveOperations<any, import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): boolean;
        count(): number;
        every(predicate: (value: TypeIndexRegistration, index?: number | undefined, array?: TypeIndexRegistration[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: TypeIndexRegistration, index?: number | undefined, array?: TypeIndexRegistration[] | undefined) => boolean): TypeIndexRegistration[];
        filterContainedStatement(predicate: (value: TypeIndexStatement, index?: number | undefined, array?: TypeIndexStatement[] | undefined) => boolean): TypeIndexStatement[];
        find(predicate: (value: TypeIndexRegistration, index?: number | undefined, obj?: TypeIndexRegistration[] | undefined) => boolean, thisArg?: any): TypeIndexRegistration | undefined;
        findIndex(predicate: (value: TypeIndexRegistration, index?: number | undefined, obj?: TypeIndexRegistration[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: TypeIndexRegistration, index?: number | undefined, array?: TypeIndexRegistration[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: TypeIndexStatement, index?: number | undefined, array?: TypeIndexStatement[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: TypeIndexRegistration, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: TypeIndexRegistration, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: TypeIndexRegistration, index?: number | undefined, array?: TypeIndexRegistration[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: TypeIndexRegistration, currentValue: TypeIndexRegistration, currentIndex: number, array: TypeIndexRegistration[]) => import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): TypeIndexRegistration;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: TypeIndexRegistration, index?: number | undefined, array?: TypeIndexRegistration[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<TypeIndexRegistration, any, undefined>;
        createThingAboutSelf(): Thing<TypeIndexStatement>;
        addThing(other: import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): TypeIndexRegistration;
        addThingAll(others: Iterable<import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): TypeIndexRegistration[];
        addThingAboutSelf(other: import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): Thing<TypeIndexStatement>;
        addThingAboutSelfAll(others: Iterable<import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): Thing<TypeIndexStatement>[];
        createStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, datatype?: string | undefined, language?: string | undefined): TypeIndexStatement;
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): TypeIndexStatement;
        addStatement(other: import("../core/Statement.js").StatementWithDestructiveOperations): TypeIndexStatement;
        addStatementAll(others: Iterable<import("../core/Statement.js").StatementWithDestructiveOperations>): TypeIndexStatement[];
        addStatementAboutSelf(other: import("../core/Statement.js").StatementWithDestructiveOperations): TypeIndexStatement;
        addStatementAboutSelfAll(others: Iterable<import("../core/Statement.js").StatementWithDestructiveOperations>): TypeIndexStatement[];
        setThing(thing: TypeIndexRegistration, uri?: string | undefined): TypeIndexRegistration;
        setThingAt(index: number, thing: TypeIndexRegistration): TypeIndexRegistration;
        setStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): TypeIndexStatement;
        setStatementAboutSelf(property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): TypeIndexStatement;
        removeThing(thingOrUri: string | import("../core/Common.js").Resource): boolean;
        removeStatement(statement: import("../core/Statement.js").StatementWithDestructiveOperations): boolean;
        removeStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, language?: string | undefined): boolean;
        pop(): TypeIndexRegistration | undefined;
        reverse(): void;
        shift(): TypeIndexRegistration | undefined;
        sort(compareFn?: ((a: TypeIndexRegistration, b: TypeIndexRegistration) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined): TypeIndexRegistration[];
        splice(start: number, deleteCount: number, ...items: TypeIndexRegistration[]): TypeIndexRegistration[];
    };
} & TBase;
export declare function TypeIndexRegistrationMixin<TStatementImpl extends StatementConstructor<Statement>, TBase extends ThingConstructor<Thing<TypeIndexStatement>>>(Base: TBase, StatementImpl: TStatementImpl): {
    new (...args: any[]): {
        toString(): string;
        getInstanceAndInstanceContainerAll(): string[];
        isForClass(forClass: string): boolean;
        getFirstElementOrNull(collection: string[]): string | null;
        addForClass(forClass: string): this;
        addInstance(instance: string): this;
        addInstanceContainer(instanceContainer: string): this;
        getForClass(): string | null;
        getForClassAll(): string[];
        getInstance(): string | null;
        getInstanceAll(): string[];
        getInstanceContainer(): string | null;
        getInstanceContainerAll(): string[];
        setForClass(forClass: string): this;
        removeForClass(forClass: string): this;
        removeInstance(instance: string): this;
        removeInstanceContainer(instanceContainer: string): this;
        removeForClassAll(): this;
        removeInstanceAll(): this;
        removeInstanceContainerAll(): this;
        toCopy(): ThisType<any>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common.js").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        getStatement(property: string, language?: string | undefined): TypeIndexStatement | undefined;
        getStatementAll(property?: string | undefined, language?: string | undefined): TypeIndexStatement[];
        hasStatement(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): TypeIndexStatement | undefined;
        contains(other: import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): boolean;
        count(): number;
        every(predicate: (value: TypeIndexStatement, index?: number | undefined, array?: TypeIndexStatement[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: TypeIndexStatement, index?: number | undefined, array?: TypeIndexStatement[] | undefined) => boolean): TypeIndexStatement[];
        find(predicate: (value: TypeIndexStatement, index?: number | undefined, obj?: TypeIndexStatement[] | undefined) => boolean, thisArg?: any): TypeIndexStatement | undefined;
        findIndex(predicate: (value: TypeIndexStatement, index?: number | undefined, obj?: TypeIndexStatement[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: TypeIndexStatement, index?: number | undefined, array?: TypeIndexStatement[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: TypeIndexStatement, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: TypeIndexStatement, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: TypeIndexStatement, index?: number | undefined, array?: TypeIndexStatement[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: TypeIndexStatement, currentValue: TypeIndexStatement, currentIndex: number, array: TypeIndexStatement[]) => TypeIndexStatement): TypeIndexStatement;
        slice(start?: number | undefined, end?: number | undefined): import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>;
        some(predicate: (value: TypeIndexStatement, index?: number | undefined, array?: TypeIndexStatement[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<TypeIndexStatement, any, undefined>;
        createStatement(property: string, value: string, datatype?: string | undefined, language?: string | undefined): TypeIndexStatement;
        addStatement(other: import("../core/Statement.js").StatementWithDestructiveOperations): TypeIndexStatement;
        addStatementAll(others: Iterable<import("../core/Statement.js").StatementWithDestructiveOperations>): TypeIndexStatement[];
        setStatement(property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): TypeIndexStatement | undefined;
        deleteStatement(statement: TypeIndexStatement): boolean;
        pop(): TypeIndexStatement | undefined;
        reverse(): void;
        shift(): TypeIndexStatement | undefined;
        sort(compareFn?: ((a: TypeIndexStatement, b: TypeIndexStatement) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined, ...items: TypeIndexStatement[]): ThisType<any>;
    };
} & TBase;
export declare function TypeIndexRegistrationStatementMixin<TBase extends StatementConstructor<Statement>>(Base: TBase): {
    new (...args: any[]): {
        isForClass(forClass: string): boolean;
        isForInstance(instance: string): boolean;
        isForInstanceContainer(instanceContainer: string): boolean;
        getUri(): string;
        hasUri(): boolean;
        toCopy(): ThisType<any>;
        getSubject(): string;
        getProperty(): string;
        getValue(): string;
        getDatatype(): string | undefined;
        getLanguage(): string | undefined;
        setSubject(subject: string | import("../core/Common.js").Resource): ThisType<any>;
        setProperty(property: string): ThisType<any>;
        setValue(value: string): ThisType<any>;
        setDatatype(datatype: string): ThisType<any>;
        setLanguage(language: string): ThisType<any>;
    };
} & TBase;
//# sourceMappingURL=impl.d.ts.map