import { DocumentWithChangelogConstructor } from "../changelog/Changelog.js";
import { LocalDocument } from "./DocumentSynchronized.js";
export declare function DocumentLocalMixin<TBase extends DocumentWithChangelogConstructor<any, any>>(Base: TBase): {
    new (...args: any[]): {
        saveUpdate(): Promise<void>;
        saveNew(uri: string): Promise<void>;
        saveOverwrite(): Promise<void>;
        isLocal(): boolean;
        isDistant(): boolean;
        getDistantUri(): string | undefined;
        getDistantUriAll(): string[];
        getThingAboutSelf(): any;
        getThingAllIterator(): Iterator<import("../core/Thing.js").Thing<import("../core/Statement.js").StatementWithDestructiveOperations>, any, undefined>;
        getStatementAllIterator(): Iterator<import("../core/Statement.js").StatementWithDestructiveOperations, any, undefined>;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common.js").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        getThing(about: string | import("../core/Common.js").Resource): any;
        hasThing(about: string | import("../core/Common.js").Resource): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | import("../core/Common.js").Resource, property: string, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        getStatementAll(about: string | import("../core/Common.js").Resource, property?: string | undefined, language?: string | undefined): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        getStatementAboutSelf(property: string, language?: string | undefined): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations) | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        hasStatement(about: string | import("../core/Common.js").Resource, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: import("../core/Document.js").DocumentWithNonDestructiveOperations<any, import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        filterContainedStatement(predicate: (value: import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations, index?: number | undefined, array?: (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[] | undefined) => boolean): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations, index?: number | undefined, array?: (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): any;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        createThing(uriOrNameHint?: string | import("../core/Common.js").Resource | undefined): any;
        createThingAboutSelf(): any;
        addThing(other: import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): any;
        addThingAll(others: Iterable<import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): any[];
        addThingAboutSelf(other: import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): any;
        addThingAboutSelfAll(others: Iterable<import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): any[];
        createStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        addStatement(other: import("../core/Statement.js").StatementWithDestructiveOperations): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        addStatementAll(others: Iterable<import("../core/Statement.js").StatementWithDestructiveOperations>): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        addStatementAboutSelf(other: import("../core/Statement.js").StatementWithDestructiveOperations): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        addStatementAboutSelfAll(others: Iterable<import("../core/Statement.js").StatementWithDestructiveOperations>): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        setThing(thing: any, uri?: string | undefined): any;
        setThingAt(index: number, thing: any): any;
        setStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        setStatementAboutSelf(property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        removeThing(thingOrUri: string | import("../core/Common.js").Resource): boolean;
        removeStatement(statement: import("../core/Statement.js").StatementWithDestructiveOperations): boolean;
        removeStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, language?: string | undefined): boolean;
        pop(): any;
        reverse(): void;
        shift(): any;
        sort(compareFn?: ((a: any, b: any) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined): any[];
        splice(start: number, deleteCount: number, ...items: any[]): any[];
        getChangelog(): import("../changelog/Changelog.js").Changelog<import("../core/Statement.js").StatementWithDestructiveOperations>;
    };
} & TBase;
export declare function DocumentDistantMixin<TBase extends DocumentWithChangelogConstructor<any, any>>(Base: TBase): {
    new (...args: any[]): {
        isLocal(): boolean;
        isDistant(): boolean;
        toLocalCopy(): LocalDocument;
        getDistantUri(): string | undefined;
        getDistantUriAll(): string[];
        getThingAboutSelf(): any;
        getThingAllIterator(): Iterator<import("../core/Thing.js").Thing<import("../core/Statement.js").StatementWithDestructiveOperations>, any, undefined>;
        getStatementAllIterator(): Iterator<import("../core/Statement.js").StatementWithDestructiveOperations, any, undefined>;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common.js").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        getThing(about: string | import("../core/Common.js").Resource): any;
        hasThing(about: string | import("../core/Common.js").Resource): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | import("../core/Common.js").Resource, property: string, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        getStatementAll(about: string | import("../core/Common.js").Resource, property?: string | undefined, language?: string | undefined): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        getStatementAboutSelf(property: string, language?: string | undefined): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations) | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        hasStatement(about: string | import("../core/Common.js").Resource, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: import("../core/Document.js").DocumentWithNonDestructiveOperations<any, import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        filterContainedStatement(predicate: (value: import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations, index?: number | undefined, array?: (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[] | undefined) => boolean): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations, index?: number | undefined, array?: (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): any;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        createThing(uriOrNameHint?: string | import("../core/Common.js").Resource | undefined): any;
        createThingAboutSelf(): any;
        addThing(other: import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): any;
        addThingAll(others: Iterable<import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): any[];
        addThingAboutSelf(other: import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>): any;
        addThingAboutSelfAll(others: Iterable<import("../core/Thing.js").ThingWithNonDestructiveOperations<import("../core/Statement.js").StatementWithDestructiveOperations>>): any[];
        createStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        addStatement(other: import("../core/Statement.js").StatementWithDestructiveOperations): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        addStatementAll(others: Iterable<import("../core/Statement.js").StatementWithDestructiveOperations>): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        addStatementAboutSelf(other: import("../core/Statement.js").StatementWithDestructiveOperations): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        addStatementAboutSelfAll(others: Iterable<import("../core/Statement.js").StatementWithDestructiveOperations>): (import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations)[];
        setThing(thing: any, uri?: string | undefined): any;
        setThingAt(index: number, thing: any): any;
        setStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        setStatementAboutSelf(property: string, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Common.js").Resource & import("../core/Common.js").Copyable & import("../core/Statement.js").StatementNonDestructiveOperations & import("../core/Statement.js").StatementDestructiveOperations;
        removeThing(thingOrUri: string | import("../core/Common.js").Resource): boolean;
        removeStatement(statement: import("../core/Statement.js").StatementWithDestructiveOperations): boolean;
        removeStatement(about: string | import("../core/Common.js").Resource, property: string, value: string, language?: string | undefined): boolean;
        pop(): any;
        reverse(): void;
        shift(): any;
        sort(compareFn?: ((a: any, b: any) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined): any[];
        splice(start: number, deleteCount: number, ...items: any[]): any[];
        getChangelog(): import("../changelog/Changelog.js").Changelog<import("../core/Statement.js").StatementWithDestructiveOperations>;
    };
} & TBase;
//# sourceMappingURL=DocumentSynchronizedImpl.d.ts.map