import { WithChangelog } from "../changelog/Changelog.js";
import { DocumentWritable } from "../core/Document.js";
import { Thing } from "../core/Thing.js";
import { LocalDocument } from "./DocumentSynchronized.js";
export type DocumentLocalConstructor<ContainedThing extends Thing<any> = Thing, SelfDescribingThing extends Thing<any> = Thing> = new (...args: any[]) => DocumentWritable<ContainedThing, SelfDescribingThing> & WithChangelog;
export declare function DocumentLocalMixin<TBase extends DocumentLocalConstructor<any, any>>(Base: TBase): {
    new (...args: any[]): {
        saveUpdate(): Promise<void>;
        saveNew(uri: string): Promise<void>;
        saveOverwrite(): Promise<void>;
        isLocal(): boolean;
        isDistant(): boolean;
        getDistantUri(): string | undefined;
        getDistantUriAll(): string[];
        createThing(): any;
        createThingAboutSelf(): any;
        addThing(other: Thing<import("../core/Statement.js").Statement>): any;
        addThingAll(others: Iterable<Thing<import("../core/Statement.js").Statement>>): any[];
        addThingAboutSelf(other: Thing<import("../core/Statement.js").Statement>): any;
        addThingAboutSelfAll(others: Iterable<Thing<import("../core/Statement.js").Statement>>): any[];
        createStatement(about: any, property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement;
        addStatement(other: import("../core/Statement.js").Statement): import("../core/Statement.js").Statement;
        addStatementAll(others: Iterable<import("../core/Statement.js").Statement>): import("../core/Statement.js").Statement[];
        addStatementAboutSelf(other: import("../core/Statement.js").Statement): import("../core/Statement.js").Statement;
        addStatementAboutSelfAll(others: Iterable<import("../core/Statement.js").Statement>): import("../core/Statement.js").Statement[];
        setStatement(about: any, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        setStatementAboutSelf(value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        deleteThing(thingOrUri: string | Thing<import("../core/Statement.js").Statement>): boolean;
        deleteStatement(statement: import("../core/Statement.js").Statement): boolean;
        pop(): any;
        reverse(): void;
        shift(): any;
        sort(compareFn?: ((a: any, b: any) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined, ...items: any[]): ThisType<any>;
        getThing(about: string): any;
        getThingAboutSelf(): any;
        hasThing(about: string): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | Thing<import("../core/Statement.js").Statement>, property: string, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        getStatementAll(about: string | Thing<import("../core/Statement.js").Statement>, property?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement[];
        getStatementAboutSelf(property: string, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement[];
        hasStatement(about: string | Thing<import("../core/Statement.js").Statement>, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: import("../core/Document.js").Document<any, Thing<import("../core/Statement.js").Statement>>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        filterContainedStatement(predicate: (value: import("../core/Statement.js").Statement, index?: number | undefined, array?: import("../core/Statement.js").Statement[] | undefined) => boolean): import("../core/Statement.js").Statement[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: import("../core/Statement.js").Statement, index?: number | undefined, array?: import("../core/Statement.js").Statement[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => Thing<import("../core/Statement.js").Statement>): any;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common.js").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        deleteContext(): void;
        setContext(context: import("../core/Common.js").Context): void;
        getChangelog(): import("../changelog/Changelog.js").Changelog<import("../core/Statement.js").Statement>;
    };
} & TBase;
export declare function DocumentDistantMixin<TBase extends DocumentLocalConstructor<any, any>>(Base: TBase): {
    new (...args: any[]): {
        isLocal(): boolean;
        isDistant(): boolean;
        toLocalCopy(): LocalDocument;
        getDistantUri(): string | undefined;
        getDistantUriAll(): string[];
        createThing(): any;
        createThingAboutSelf(): any;
        addThing(other: Thing<import("../core/Statement.js").Statement>): any;
        addThingAll(others: Iterable<Thing<import("../core/Statement.js").Statement>>): any[];
        addThingAboutSelf(other: Thing<import("../core/Statement.js").Statement>): any;
        addThingAboutSelfAll(others: Iterable<Thing<import("../core/Statement.js").Statement>>): any[];
        createStatement(about: any, property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        createStatementAboutSelf(property: string, value: string, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement;
        addStatement(other: import("../core/Statement.js").Statement): import("../core/Statement.js").Statement;
        addStatementAll(others: Iterable<import("../core/Statement.js").Statement>): import("../core/Statement.js").Statement[];
        addStatementAboutSelf(other: import("../core/Statement.js").Statement): import("../core/Statement.js").Statement;
        addStatementAboutSelfAll(others: Iterable<import("../core/Statement.js").Statement>): import("../core/Statement.js").Statement[];
        setStatement(about: any, value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        setStatementAboutSelf(value: string, oldValue?: string | undefined, datatype?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        deleteThing(thingOrUri: string | Thing<import("../core/Statement.js").Statement>): boolean;
        deleteStatement(statement: import("../core/Statement.js").Statement): boolean;
        pop(): any;
        reverse(): void;
        shift(): any;
        sort(compareFn?: ((a: any, b: any) => number) | undefined): ThisType<any>;
        splice(start: number, deleteCount?: number | undefined, ...items: any[]): ThisType<any>;
        getThing(about: string): any;
        getThingAboutSelf(): any;
        hasThing(about: string): boolean;
        hasThingAboutSelf(): boolean;
        getStatement(about: string | Thing<import("../core/Statement.js").Statement>, property: string, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        getStatementAll(about: string | Thing<import("../core/Statement.js").Statement>, property?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement[];
        getStatementAboutSelf(property: string, language?: string | undefined): import("../core/Statement.js").Statement | undefined;
        getStatementAboutSelfAll(property?: string | undefined, language?: string | undefined): import("../core/Statement.js").Statement[];
        hasStatement(about: string | Thing<import("../core/Statement.js").Statement>, property?: string | undefined, language?: string | undefined): boolean;
        hasStatementAboutSelf(property?: string | undefined, language?: string | undefined): boolean;
        at(index: number): any;
        contains(other: import("../core/Document.js").Document<any, Thing<import("../core/Statement.js").Statement>>): boolean;
        count(): number;
        every(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean, thisArg?: any): boolean;
        filter(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => boolean): any[];
        filterContainedStatement(predicate: (value: import("../core/Statement.js").Statement, index?: number | undefined, array?: import("../core/Statement.js").Statement[] | undefined) => boolean): import("../core/Statement.js").Statement[];
        find(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => boolean, thisArg?: any): any;
        findIndex(predicate: (value: any, index?: number | undefined, obj?: any[] | undefined) => unknown, thisArg?: any): number;
        forEach(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => void, thisArg?: any): void;
        forEachStatement(callbackfn: (value: import("../core/Statement.js").Statement, index?: number | undefined, array?: import("../core/Statement.js").Statement[] | undefined) => void, thisArg?: any): void;
        includes(searchElement: any, fromIndex?: number | undefined): boolean;
        indexOf(searchElement: any, fromIndex?: number | undefined): number;
        keys(): IterableIterator<number>;
        map(callbackfn: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): unknown[];
        reduce(callbackfn: (previousValue: any, currentValue: any, currentIndex: number, array: any[]) => Thing<import("../core/Statement.js").Statement>): any;
        slice(start?: number | undefined, end?: number | undefined): ThisType<any>;
        some(predicate: (value: any, index?: number | undefined, array?: any[] | undefined) => unknown, thisArg?: any): boolean;
        [Symbol.iterator](): Iterator<any, any, undefined>;
        getUri(): string;
        hasUri(): boolean;
        getContext(): import("../core/Common.js").Context | undefined;
        equals(other: ThisType<any>): boolean;
        difference(other: ThisType<any>): ThisType<any>;
        toCopy(): ThisType<any>;
        deleteContext(): void;
        setContext(context: import("../core/Common.js").Context): void;
        getChangelog(): import("../changelog/Changelog.js").Changelog<import("../core/Statement.js").Statement>;
    };
} & TBase;
//# sourceMappingURL=DocumentSynchronizedImpl.d.ts.map